# Generated by Django 2.1.9 on 2020-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200731_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('Add_Date', models.DateTimeField(auto_now=True)),
                ('Order_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Customer_ID', models.CharField(default='Not Availiable', max_length=50)),
                ('Pay_ID', models.CharField(default='Not Availiable', max_length=50)),
            ],
            options={
                'db_table': 'OrderData',
            },
        ),
        migrations.CreateModel(
            name='OrderMenuData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_ID', models.CharField(max_length=50)),
                ('Order_ID', models.CharField(max_length=100)),
                ('Quantity', models.CharField(default='1', max_length=50)),
            ],
            options={
                'db_table': 'OrderMenuData',
            },
        ),
    ]
