# Generated by Django 2.1.9 on 2020-08-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderdata_ordermenudata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('Add_Date', models.DateTimeField(auto_now=True)),
                ('Customer_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.CharField(default='Not Availiable', max_length=200)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'CustomerData',
            },
        ),
    ]
