# Generated by Django 2.1.9 on 2020-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200812_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='Status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='Add_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
