# Generated by Django 2.1.9 on 2020-08-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200814_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tax', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'TaxData',
            },
        ),
    ]
