# Generated by Django 2.1.9 on 2020-08-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_taxdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdata',
            name='AmountwithTax',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
