# Generated by Django 2.1.9 on 2020-08-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_paymentdata_amountwithtax'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coins_Count', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'CoinsData',
            },
        ),
        migrations.AddField(
            model_name='customerdata',
            name='Coins_Wallet',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
