# Generated by Django 2.1.9 on 2020-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200822_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudata',
            name='Discount',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
