# Generated by Django 2.1.9 on 2020-08-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_menudata_discount'),
        ('app', '0011_orderdata_table_no'),
    ]

    operations = [
    ]
