# Generated by Django 2.1.9 on 2020-08-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20200827_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=15)),
                ('TaxAmount', models.CharField(max_length=10)),
                ('Tax', models.CharField(max_length=10)),
                ('Date', models.CharField(max_length=10)),
                ('AmountwithTax', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('Pay_ID', models.CharField(max_length=10)),
                ('PayMode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'InvoiceData',
            },
        ),
    ]
