# Generated by Django 2.1.9 on 2020-09-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_invoicedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCouponData',
            fields=[
                ('Coupon_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Coupon_Nmae', models.CharField(max_length=50)),
                ('Coupon_Code', models.CharField(max_length=50)),
                ('Discount_Percentage', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DiscountCouponData',
            },
        ),
    ]
