# Generated by Django 2.1.9 on 2020-09-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_discountcoupondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcoupondata',
            old_name='Coupon_Nmae',
            new_name='Coupon_Name',
        ),
    ]
