# Generated by Django 2.1.9 on 2020-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200918_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupondata',
            name='Status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='discountcoupondata',
            name='Used',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
