# Generated by Django 2.1.9 on 2020-09-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200919_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdata',
            name='AmountPaid',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='Promocode',
            field=models.CharField(default='Not Applied', max_length=50),
        ),
    ]
