# Generated by Django 2.1.9 on 2020-09-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200919_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='AmountPaid',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='Promocode',
            field=models.CharField(default='Not Applied', max_length=50),
        ),
    ]
