# Generated by Django 2.1.9 on 2020-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_menudata_item_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager_Password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ManagerData',
            },
        ),
    ]
