# Generated by Django 2.1.9 on 2020-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_managerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'AdminData',
            },
        ),
    ]
